### ISSUE TITLE
Expose colors

### ISSUE THREAD

**Issue by gonzaloserrano** [leisiji/interestingwords.nvim#1]
Thanks a lot for your plugin.

It would be great to allow adding more colors setting some var, I usually use more than 6.

Have a good day,

**Comment by leisiji** [comment]
@gonzaloserrano You can update to the latest and change the default colors by setting the `vim.g.interestingwords_colors` (lua)

**Comment by gonzaloserrano** [comment]
Wow, that was quick. Thanks a lot! 💯

**Comment by gonzaloserrano** [comment]
In case someone finds it useful:
```vim
vim.g.interestingwords_colors = {'#8CCBEA', '#A4E57E', '#FFDB72', '#FF7272', '#FFB3FF', '#9999FF', '#F4A261', '#2A9D8F'}
```
![CleanShot 2021-11-10 at 10 39 10](https://user-images.githubusercontent.com/349328/141088647-cd58a1a7-4b19-4802-b2a8-9ffa0d70673b.png)
